
version: '3.3'
services:

  hl7-auth-db:
      image: mongo:4.4.29-focal
      networks:
        - hl7
      container_name: hl7-auth-db
      expose:
            - "27017"
      healthcheck:
          test: ["CMD-SHELL", "mongo localhost:27017 --eval 'db.serverStatus()' "]
          interval: 30s
          timeout: 30s
          retries: 3
      volumes:
          - ../../data/hl7-auth-db/logs/:/var/log/mongodb/
          - ../../data/hl7-auth-db/db:/data/db
          - ../../data/hl7-auth-db/configdb:/data/configdb
      env_file:
          - ./config/hl7-auth-db.env
      restart: always

  hl7-auth:
      image: nist775hit/hl7-auth-2
      networks:
        - hl7
      container_name: hl7-auth
      expose:
          - "8090"
      ports:
          - "8090:8090"
      depends_on:
        - hl7-auth-db
      env_file:
          - ./hl7-auth-db/config/db.env
          - ./config/hl7-auth.env
      links:
          - hl7-auth-db:hl7-auth-db
      volumes:
          - ../../data/hl7-auth/logs/:/var/log/hl7-auth/
          - ./config/keys:/usr/local/hl7-auth/keys

  hl7-igamt-db:
      image: mongo:4.4.29-focal
      networks:
        - hl7
      container_name: hl7-igamt-db
      expose:
            - "27017"
      healthcheck:
          test: ["CMD-SHELL", "mongo localhost:27017 --eval 'db.serverStatus()' "]
          interval: 30s
          timeout: 30s
          retries: 3
      volumes:
          - ../../data/hl7-igamt-db/logs/:/var/log/mongodb/
          - ../../data/hl7-igamt-db/db:/data/db
          - ../../data/hl7-igamt-db/configdb:/data/configdb
      env_file:
          - ./config/hl7-igamt-db.env
      restart: always

  hl7-igamt:
      image: nist775hit/hl7-igamt-2
      networks:
        - hl7
      expose:
          - "9000"
      ports:
          - "9000:9000"
      container_name: hl7-igamt
      depends_on:
        - hl7-igamt-db
        - hl7-auth
      env_file:
        - ./hl7-igamt-db/config/db.env
        - ./config/hl7-igamt.env
      links:
          - hl7-igamt-db:hl7-igamt-db
          - hl7-auth:hl7-auth
      volumes:
          - ../../data/hl7-igamt/logs/:/var/log/hl7-igamt/
          - ./config/keys:/usr/local/hl7-igamt/keys

      extra_hosts:
          - "hit-dev.nist.gov:129.6.24.81"

  hl7-reverse-proxy:
      build: ./tools-reverse-proxy
      networks:
        - hl7
      image: hl7-reverse-proxy
      container_name: hl7-reverse-proxy
      volumes:
          - ../../data/hl7-reverse-proxy/logs/:/var/log/nginx/
          - ../../data/hl7-reverse-proxy/html:/usr/share/nginx/html:ro
      ports:
          #- "80:80"
          - "8102:8102"
      depends_on:
          - hl7-auth
          - hl7-igamt
      links:
          - hl7-auth:hl7-auth
          - hl7-igamt:hl7-igamt

networks:
  hl7:
